import React from "react"
import Button from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/13fdTVdoIfczIUDi5dncur/code-connect-test?node-id=4-10&node-type=symbol&t=T8SXJBmwIRbvLxTh-0",
  {
    props: {},
    example: () => <Button />,
  },
)
