import Paragraph from "./Paragraph"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Paragraph,
  "https://www.figma.com/design/13fdTVdoIfczIUDi5dncur/code-connect-test?node-id=16-36&node-type=frame&t=T8SXJBmwIRbvLxTh-0",
  {
    props: {
        uppercase: figma.enum("uppercase", {
            default: "default",
            uppercase: "uppercase",
        }),
    },
      example: (props) => <Paragraph uppercase={props.uppercase}>Paragraph</Paragraph>,
  },
)
